name: Lint and Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip pip-tools
          python -m pip install -r requirements.txt
      - run: python -m black --check --diff .
      - run: python -m isort --check --diff .
      - run: python -m flake8 .
      - run: python -m pyright .
      - name: Test - Pytest
        run: |
          pytest --cov-report term --cov-report xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
